Adds support for list type inputs
opentensor/btcli pull request #103
Opened 2024-09-20 21:24 UTC by ibraheem-opentensor

- Users can now use `--netuid 1,2,3,4` or `--netuid "1, 2, 3, 4"` instead of `-n 1 -n 2 -n 3`
- Extended to netuids, weights, salt

2024-09-21 08:29 UTC, thewhaleking requested changes

2024-09-21 08:29 UTC, thewhaleking commented on bittensor_cli/cli.py
>          help="Set the netuid(s) to filter by. Separate multiple netuids with a space, for example: `0 1 2`.",
Needs updated

2024-09-21 08:29 UTC, thewhaleking commented on bittensor_cli/cli.py
>          help="Weights for the specified UIDs, e.g. `-w 0.2 -w 0.4 -w 0.1 ...` Must correspond to the order of the UIDs.",
Needs updated

2024-09-21 18:43 UTC, thewhaleking approved these changes

2024-09-22 08:59 UTC, thewhaleking commented
Approved, but do we want to do the same thing for `--include-hotkeys`, `--exclude-hotkeys`, and the like?

2024-09-23 16:10 UTC, thewhaleking approved these changes

2024-09-23 16:11 UTC, ibraheem-opentensor commented
> Approved, but do we want to do the same thing for `--include-hotkeys`, `--exclude-hotkeys`, and the like?

Great call - let me implement this there too; then we can merge in one go

2024-09-23 20:00 UTC, thewhaleking approved these changes

2024-09-23 20:29 UTC, merged